version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - REACT_APP_GRAPHQL_API_URL=${REACT_APP_GRAPHQL_API_URL}
    environment:
      - PORT=3000
    ports:
      - "${PORT}:3000"
